services:
  salty-ocean-api:
    container_name: salty-ocean-api
    build: .
    ports:
      - "8080:5010"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=5010
      # Gunicorn specific settings
      - WORKERS_PER_CORE=1
      - WEB_CONCURRENCY=4  # Override default workers calculation
      - TIMEOUT=120
      # Resource limits to prevent OOM
      - MAX_WORKERS=4
    networks:
      - salty_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  salty_network:
    external: true
