services:
  salty-ocean-api:
    container_name: salty-ocean-api
    build: .
    ports:
      - "5010:5010"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=5010
      - CORS_ORIGINS=*
      - REDIS_URL=redis://redis:6379
    networks:
      - salty_network
    restart: unless-stopped

networks:
  salty_network:
    external: true
