services:
  salty-ocean-api:
    container_name: salty-ocean-api
    build: .
    ports:
      - "8080:5010"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=5010
      # Gunicorn specific settings
      - WORKERS_PER_CORE=1
      - WEB_CONCURRENCY=1  # Single worker to avoid state conflicts
      - TIMEOUT=300  # Increased timeout for GFS downloads
      # Resource limits to prevent OOM
      - MAX_WORKERS=1
    networks:
      - salty_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 30s  # Reduced since we're just checking basic health

networks:
  salty_network:
    external: true
