services:
  salty-ocean-api:
    container_name: salty-ocean-api
    build: .
    ports:
      - "8080:5010"
    volumes:
      - ./data:/usr/src/app/data
      - ./logs:/usr/src/app/logs
    environment:
      - NODE_ENV=production
      - PORT=5010
    networks:
      - salty_network
    restart: unless-stopped

networks:
  salty_network:
    external: true
