services:
  salty-ocean-api:
    container_name: salty-ocean-api
    build: .
    ports:
      - "5010:5010"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=5010
      - CORS_ORIGINS=*
      - REDIS_URL=redis://redis:6379
    networks:
      - salty_network
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    container_name: salty-ocean-redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - salty_network
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

networks:
  salty_network:
    external: true

volumes:
  redis_data:
