name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ../salty-ocean-api
            git pull origin main

            echo "Stopping and removing existing containers..."
            docker-compose stop salty-ocean-api
            docker-compose rm -f salty-ocean-api

            echo "Building and starting new container..."
            docker-compose build --no-cache salty-ocean-api
            docker-compose up -d salty-ocean-api
